### ISSUE TITLE
Hawtio can't be accessed properly by a user with just a viewer permission

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio-online#424]
When being logged in as a user with the following role: 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hawtio-viewer
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
  verbs:
  - create
```

the current version of hawtio on the `main` branch disabled connecting to the apps because of 403 response from the respective `/jolokia/version` urls of the applications. The TP1 release allows connecting to the application, the JMX and Camel plugins seem to work fine, but the Runtime page just logs out the user.
