### ISSUE TITLE
Support different Jolokia ports & paths

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-online#66]
If I'm not mistaken, currently hawtio-online hardcodes the Jolokia port to `8778` and assumes it's available at `/jolokia`. However, for instance Artemis broker exposes the Jolokia endpoint with the following port and the path `/console/jolokia` by default:
```yaml
      ports:
        - containerPort: 8161
          name: console-jolokia
          protocol: TCP
```

The main focus here is to recognise Artemis brokers on OpenShift but it would be also flexible that hawtio-online can pick up arbitrary port numbers and Jolokia paths given they are specified in the application deployment spec.

**Comment by tadayosi** [comment]
@astefanutti Is there a good way to specify the Jolokia path in an application deployment spec?  I don't think `spec.containers[].ports[]` accepts key like `path`. Should we introduce an env variable like `HAWTIO_JOLOKIA_PATH` as follows?
```yaml
spec:
  containers:
    - env:
        - name: HAWTIO_JOLOKIA_PATH
          value: /console/jolokia
```

**Comment by astefanutti** [comment]
@tadayosi right, while the port can be retrieve from the container port, the path would have to be provided elsewhere in the pod metadata. I would think an annotation would be the best place, e.g.:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: artemis-broker
  annotations:
   "hawt.io/jolokiaPath": /console/jolokia
```
